spring:
  application:
    name: mail-service
  mail:
    host: smtp.gmail.com
    username: student.service.bsuir@gmail.com
    password: hotachhaokndqfak
    port: 587
  kafka:
    bootstrap-servers: localhost:9092
    topic: notifications-topic
    consumer:
      group-id: notifications-group
server:
  port: 8050
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka